openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'BarStock Back-End'
  description: Endpoint for businesses to create an account.
paths:
  /businesses/account:
    get:
      description: If the request is successful, a 200 status code will be returned, along with the bussiness's account information, their distributor's information, and their representative's information. A 404 status code will be returned if the API key is invalid.
      parameters:
        - in: query
          name: api_key
          required: true
          schema:
            type: string
            example: jgn983hy48thw9begh98h4539h4
          description: The business's api_key.
      responses:
        '200':
          description: Account details request was successful.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    business:
                      type: object
                      example:
                        data:
                          id: '1'
                          type: business
                          attributes:
                            id: 1
                            name: The Basement
                            address: 78295 US Highway 40 Winter Park, CO
                            email: mike@thebasement.com
                            phone_number: 9703637280
                            distributor:
                              distributor_address: 8000 Southpark Terrace, Littleton, CO 80120
                              distributor_name: RNDC
                            representative:
                              rep_name: Andy
                              rep_email: andy@gmail.com
                              rep_phone_number: 7205038000
        '404':
          description: Unsuccessful request, the api_key with either not provided or is invalid and could not be associated with a business instance in the database.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Couldn't find Business

  /businesses/login:
    post:
      description: |
        If the request is successful, a 200 status code will be returned, along with an api_key. A 404 status code will be returned if the business's email cannot be found in the database. A 401 status code will be returned if the password is incorrect.
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
            example: my_email@example.com
          description: The business's unique email.
        - in: query
          name: password
          required: true
          schema:
            type: string
            example: password123
          description: The business's password.
      responses:
        '200':
          description: The log-in request was successful.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                      example: a9hb9xW4-AhbiLIBW89jcw
        '404':
          description: Unsuccessful request, the business's email was either not provided, or could not be found in the database.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Couldn't find Business
        '401':
          description: Unsuccessful request, the password was either not provided, or is invalid.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    unauth:
                      type: string
                      example: Incorrect Password

  /businesses/register:
    post:
      description: If the request is successful, a 201 status code will be returned and a business will be created, saved to the database, and the response will include an api_key. An unsuccessful request will return a 422 error.
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            example: Mike's Bar
          description: The business's name.
        - in: query
          name: email
          required: true
          schema:
            type: string
            example: inventory@mikesbar.com
          description: The business's email.
        - in: query
          name: password
          required: true
          schema:
            type: string
            example: password123
          description: The business's password.
        - in: query
          name: phone_number
          required: true
          schema:
            type: string
            example: 3039994444
          description: The business's phone number.
        - in: query
          name: distributor_code
          required: true
          schema:
            type: string
            example: CODE1234
          description: The business's distributor_code.
        - in: query
          name: address
          required: true
          schema:
            type: string
            example: 100 Main St Winter Park, CO 80482
          description: The business's address.
      responses:
        '201':
          description: The business record has been created and saved to the database.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                      example: a9hb9xW4-AhbiLIBW89jcw

        '422':
          description: Unprocessable Entity - The request was well formed, but was unable to be followed due to semantic errors.
          content:
              application/json:
                schema:
                  type: object
          $ref: ''
          examples:
              Email Already Exists:
                  email:
                  - has already been taken
              Distributor Code Is Not Included / Not Valid:
                  distributor:
                    - must exist
              Password Is Not Included:
                  password:
                    - can't be blank
              Address Is Not Included:
                  address:
                    - can't be blank
              Phone Number Is Not Included:
                  phone number:
                    - can't be blank
                    - is not a number
              Phone Number Is Not A Number:
                  phone number:
                    - is not a number
  /distributors/login:
    post:
      description: If the request is successful, a 200 status code will be returned, along with an api_key. A 404 status code will be returned if the distibutor's name cannot be found in the database. A 401 status code will be returned if the password is incorrect.
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            example: RNDC
          description: The distrutor's unique name.
        - in: query
          name: password
          required: true
          schema:
            type: string
            example: password123
          description: The distributor's password.
      responses:
        '200':
          description: The log-in request was successful.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                      example: a9hb9xW4-AhbiLIBW89jcw
        '404':
          description: Unsuccessful request, the distributor's name was either not provided, or could not be found in the database.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Couldn't find Distributor
        '401':
          description: Unsuccessful request, the password was either not provided, or is invalid.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    unauth:
                      type: string
                      example: Incorrect Password
  /items:
    get:
      description: If the request is successful, a 200 status code will be returned, along with a list of items. A 404 status code will be returned if the api_key is not provided, or is incorrect aka the business cannot be found by that api_key.
      parameters:
        - in: query
          name: api_key
          required: true
          schema:
            type: string
            example: jgn983hy48thw9begh98h4539h4
          description: The business's api_key.
      responses:
        '200':
          description: The items request was successful.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                      example:
                        data:
                        - id: '1'
                          type: item
                          attributes:
                            alc_type: Alc type 1
                            alc_category: Alc category 1
                            name: Item 1
                            price: 3
                            ounces: 6.6
                            unit: Unit 1
                            thumbnail: https://picsum.photos/id/755/200/200?grayscale
                        - id: '2'
                          type: item
                          attributes:
                            alc_type: Alc type 2
                            alc_category: Alc category 2
                            name: Item 2
                            price: 4.5
                            ounces: 9.9
                            unit: Unit 2
                            thumbnail: https://picsum.photos/id/755/200/200?grayscale
        '404':
          description: Unsuccessful request, the api_key with either not provided or could not be associated with an instance of a business in the database.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Couldn't find Business

servers:
  - description: Heroku Endpoint
    url: https://barstock-backend.herokuapp.com/api/v1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BarStock/BarStockBackEnd/1.0.0
